services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PROXY_PASS_HOST=go-app
      - PROXY_PASS_PORT=8080
  go-app: 
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/workspaces
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=todo_user
      - DB_PASSWORD=todo_user
    tty: true
  db:
    image: mysql:8.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_demo
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=todo_user
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
