name: Push Docker Image to ECR
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'
      ecr_repository_name:
        description: 'ECR repository name'
        required: true
        default: 'todo-go-app'
env:
  AWS_REGION: ap-northeast-1
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_FOR_GITHUB_ACTIONS: ${{ secrets.AWS_ROLE_FOR_GITHUB_ACTIONS }} # IAMロールのARN
  BUCKET_NAME: s3://kentugu-app-resources # go appバイナリの保存先バケット
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 参考： https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services 
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_FOR_GITHUB_ACTIONS }}
          role-session-name: GitHubActions # デフォルト名と同じ

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: Build and push go app image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -f ./docker/golang/Dockerfile \
            -t ${{ env.AWS_ACCOUNT_ID}}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ github.event.inputs.ecr_repository_name }}:${{ github.event.inputs.image_tag }} \
            .

      - name: Build and push Fluent-Bit image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -f ./docker/fluentbit/Dockerfile \
            -t ${{ env.AWS_ACCOUNT_ID}}.dkr.ecr.ap-northeast-1.amazonaws.com/fluentbit:${{ github.event.inputs.image_tag }} \
            .
      
      - name: Setup Go 1.23.2
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Install dependencies
        run: |
          go mod tidy
      
      - name: Build go app
        run: |
          go build -o /usr/local/bin/server .
          chmod +x /usr/local/bin/server

      - name: Upload go app binary to S3
        run: |
          aws s3 cp /usr/local/bin/server s3://${{ env.BUCKET_NAME }}/${{ github.event.inputs.ecr_repository_name }}/
